//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: FreezeService.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// The request and responses for freeze service. 
///
/// Usage: instantiate `Proto_FreezeServiceClient`, then call methods of this protocol to make API calls.
public protocol Proto_FreezeServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Proto_FreezeServiceClientInterceptorFactoryProtocol? { get }

  func freeze(
    _ request: Proto_Transaction,
    callOptions: CallOptions?
  ) -> UnaryCall<Proto_Transaction, Proto_TransactionResponse>
}

extension Proto_FreezeServiceClientProtocol {
  public var serviceName: String {
    return "proto.FreezeService"
  }

  /// Freezes the nodes by submitting the transaction. The grpc server returns the TransactionResponse
  ///
  /// - Parameters:
  ///   - request: Request to send to freeze.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func freeze(
    _ request: Proto_Transaction,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Proto_Transaction, Proto_TransactionResponse> {
    return self.makeUnaryCall(
      path: "/proto.FreezeService/freeze",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makefreezeInterceptors() ?? []
    )
  }
}

public protocol Proto_FreezeServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'freeze'.
  func makefreezeInterceptors() -> [ClientInterceptor<Proto_Transaction, Proto_TransactionResponse>]
}

public final class Proto_FreezeServiceClient: Proto_FreezeServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Proto_FreezeServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the proto.FreezeService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Proto_FreezeServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// The request and responses for freeze service. 
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Proto_FreezeServiceProvider: CallHandlerProvider {
  var interceptors: Proto_FreezeServiceServerInterceptorFactoryProtocol? { get }

  /// Freezes the nodes by submitting the transaction. The grpc server returns the TransactionResponse
  func freeze(request: Proto_Transaction, context: StatusOnlyCallContext) -> EventLoopFuture<Proto_TransactionResponse>
}

extension Proto_FreezeServiceProvider {
  public var serviceName: Substring { return "proto.FreezeService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "freeze":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Proto_Transaction>(),
        responseSerializer: ProtobufSerializer<Proto_TransactionResponse>(),
        interceptors: self.interceptors?.makefreezeInterceptors() ?? [],
        userFunction: self.freeze(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol Proto_FreezeServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'freeze'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makefreezeInterceptors() -> [ServerInterceptor<Proto_Transaction, Proto_TransactionResponse>]
}
