// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ResponseCode.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Proto_ResponseCodeEnum: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// The transaction passed the precheck validations.
  case ok // = 0

  /// For any error not handled by specific error codes listed below.
  case invalidTransaction // = 1

  ///Payer account does not exist.
  case payerAccountNotFound // = 2

  ///Node Account provided does not match the node account of the node the transaction was submitted to.
  case invalidNodeAccount // = 3

  /// Pre-Check error when TransactionValidStart + transactionValidDuration is less than current consensus time.
  case transactionExpired // = 4

  /// Transaction start time is greater than current consensus time
  case invalidTransactionStart // = 5

  ///valid transaction duration is a positive non zero number that does not exceed 120 seconds
  case invalidTransactionDuration // = 6

  /// The transaction signature is not valid
  case invalidSignature // = 7

  ///Transaction memo size exceeded 100 bytes
  case memoTooLong // = 8

  /// The fee provided in the transaction is insufficient for this type of transaction
  case insufficientTxFee // = 9

  /// The payer account has insufficient cryptocurrency to pay the transaction fee
  case insufficientPayerBalance // = 10

  /// This transaction ID is a duplicate of one that was submitted to this node or reached consensus in the last 180 seconds (receipt period)
  case duplicateTransaction // = 11

  ///If API is throttled out
  case busy // = 12

  ///The API is not currently supported
  case notSupported // = 13

  ///The file id is invalid or does not exist
  case invalidFileID // = 14

  ///The account id is invalid or does not exist
  case invalidAccountID // = 15

  ///The contract id is invalid or does not exist
  case invalidContractID // = 16

  ///Transaction id is not valid
  case invalidTransactionID // = 17

  ///Receipt for given transaction id does not exist
  case receiptNotFound // = 18

  ///Record for given transaction id does not exist
  case recordNotFound // = 19

  ///The solidity id is invalid or entity with this solidity id does not exist
  case invalidSolidityID // = 20

  /// The responding node has submitted the transaction to the network. Its final status is still unknown.
  case unknown // = 21

  /// The transaction succeeded
  case success // = 22

  /// There was a system error and the transaction failed because of invalid request parameters.
  case failInvalid // = 23

  /// There was a system error while performing fee calculation, reserved for future.
  case failFee // = 24

  /// There was a system error while performing balance checks, reserved for future.
  case failBalance // = 25

  ///Key not provided in the transaction body
  case keyRequired // = 26

  ///Unsupported algorithm/encoding used for keys in the transaction
  case badEncoding // = 27

  ///When the account balance is not sufficient for the transfer
  case insufficientAccountBalance // = 28

  ///During an update transaction when the system is not able to find the Users Solidity address
  case invalidSolidityAddress // = 29

  ///Not enough gas was supplied to execute transaction
  case insufficientGas // = 30

  ///contract byte code size is over the limit
  case contractSizeLimitExceeded // = 31

  ///local execution (query) is requested for a function which changes state
  case localCallModificationException // = 32

  ///Contract REVERT OPCODE executed
  case contractRevertExecuted // = 33

  ///For any contract execution related error not handled by specific error codes listed above.
  case contractExecutionException // = 34

  ///In Query validation, account with +ve(amount) value should be Receiving node account, the receiver account should be only one account in the list
  case invalidReceivingNodeAccount // = 35

  /// Header is missing in Query request
  case missingQueryHeader // = 36

  /// The update of the account failed
  case accountUpdateFailed // = 37

  /// Provided key encoding was not supported by the system
  case invalidKeyEncoding // = 38

  /// null solidity address
  case nullSolidityAddress // = 39

  /// update of the contract failed
  case contractUpdateFailed // = 40

  /// the query header is invalid
  case invalidQueryHeader // = 41

  /// Invalid fee submitted
  case invalidFeeSubmitted // = 42

  /// Payer signature is invalid
  case invalidPayerSignature // = 43

  /// The keys were not provided in the request.
  case keyNotProvided // = 44

  /// Expiration time provided in the transaction was invalid.
  case invalidExpirationTime // = 45

  ///WriteAccess Control Keys are not provided for the file
  case noWaclKey // = 46

  ///The contents of file are provided as empty.
  case fileContentEmpty // = 47

  /// The crypto transfer credit and debit do not sum equal to 0
  case invalidAccountAmounts // = 48

  /// Transaction body provided is empty
  case emptyTransactionBody // = 49

  /// Invalid transaction body provided
  case invalidTransactionBody // = 50

  /// the type of key (base ed25519 key, KeyList, or ThresholdKey) does not match the type of signature (base ed25519 signature, SignatureList, or ThresholdKeySignature)
  case invalidSignatureTypeMismatchingKey // = 51

  /// the number of key (KeyList, or ThresholdKey) does not match that of signature (SignatureList, or ThresholdKeySignature). e.g. if a keyList has 3 base keys, then the corresponding signatureList should also have 3 base signatures.
  case invalidSignatureCountMismatchingKey // = 52

  /// the livehash body is empty
  case emptyLiveHashBody // = 53

  /// the livehash data is missing
  case emptyLiveHash // = 54

  /// the keys for a livehash are missing
  case emptyLiveHashKeys // = 55

  /// the livehash data is not the output of a SHA-384 digest
  case invalidLiveHashSize // = 56

  /// the query body is empty
  case emptyQueryBody // = 57

  /// the crypto livehash query is empty
  case emptyLiveHashQuery // = 58

  /// the livehash is not present
  case liveHashNotFound // = 59

  /// the account id passed has not yet been created.
  case accountIDDoesNotExist // = 60

  /// the livehash already exists for a given account
  case liveHashAlreadyExists // = 61

  /// File WACL keys are invalid
  case invalidFileWacl // = 62

  /// Serialization failure
  case serializationFailed // = 63

  /// The size of the Transaction is greater than transactionMaxBytes
  case transactionOversize // = 64

  /// The Transaction has more than 50 levels
  case transactionTooManyLayers // = 65

  ///Contract is marked as deleted
  case contractDeleted // = 66

  /// the platform node is either disconnected or lagging behind.
  case platformNotActive // = 67

  /// one public key matches more than one prefixes on the signature map
  case keyPrefixMismatch // = 68

  /// transaction not created by platform due to large backlog
  case platformTransactionNotCreated // = 69

  /// auto renewal period is not a positive number of seconds
  case invalidRenewalPeriod // = 70

  /// the response code when a smart contract id is passed for a crypto API request
  case invalidPayerAccountID // = 71

  /// the account has been marked as deleted
  case accountDeleted // = 72

  /// the file has been marked as deleted
  case fileDeleted // = 73

  /// same accounts repeated in the transfer account list
  case accountRepeatedInAccountAmounts // = 74

  /// attempting to set negative balance value for crypto account
  case settingNegativeAccountBalance // = 75

  /// when deleting smart contract that has crypto balance either transfer account or transfer smart contract is required
  case obtainerRequired // = 76

  ///when deleting smart contract that has crypto balance you can not use the same contract id as transferContractId as the one being deleted
  case obtainerSameContractID // = 77

  ///transferAccountId or transferContractId specified for contract delete does not exist
  case obtainerDoesNotExist // = 78

  ///attempting to modify (update or delete a immutable smart contract, i.e. one created without a admin key)
  case modifyingImmutableContract // = 79

  ///Unexpected exception thrown by file system functions
  case fileSystemException // = 80

  /// the duration is not a subset of [MINIMUM_AUTORENEW_DURATION,MAXIMUM_AUTORENEW_DURATION]
  case autorenewDurationNotInRange // = 81

  /// Decoding the smart contract binary to a byte array failed. Check that the input is a valid hex string.
  case errorDecodingBytestring // = 82

  /// File to create a smart contract was of length zero
  case contractFileEmpty // = 83

  /// Bytecode for smart contract is of length zero
  case contractBytecodeEmpty // = 84

  /// Attempt to set negative initial balance
  case invalidInitialBalance // = 85

  /// [Deprecated]. attempt to set negative receive record threshold
  case invalidReceiveRecordThreshold // = 86

  /// [Deprecated]. attempt to set negative send record threshold
  case invalidSendRecordThreshold // = 87

  /// Special Account Operations should be performed by only Genesis account, return this code if it is not Genesis Account
  case accountIsNotGenesisAccount // = 88

  /// The fee payer account doesn't have permission to submit such Transaction
  case payerAccountUnauthorized // = 89

  /// FreezeTransactionBody is invalid
  case invalidFreezeTransactionBody // = 90

  /// FreezeTransactionBody does not exist
  case freezeTransactionBodyNotFound // = 91

  ///Exceeded the number of accounts (both from and to) allowed for crypto transfer list
  case transferListSizeLimitExceeded // = 92

  /// Smart contract result size greater than specified maxResultSize
  case resultSizeLimitExceeded // = 93

  ///The payer account is not a special account(account 0.0.55)
  case notSpecialAccount // = 94

  /// Negative gas was offered in smart contract call
  case contractNegativeGas // = 95

  /// Negative value / initial balance was specified in a smart contract call / create
  case contractNegativeValue // = 96

  /// Failed to update fee file
  case invalidFeeFile // = 97

  /// Failed to update exchange rate file
  case invalidExchangeRateFile // = 98

  /// Payment tendered for contract local call cannot cover both the fee and the gas
  case insufficientLocalCallGas // = 99

  /// Entities with Entity ID below 1000 are not allowed to be deleted
  case entityNotAllowedToDelete // = 100

  /// Violating one of these rules: 1) treasury account can update all entities below 0.0.1000, 2) account 0.0.50 can update all entities from 0.0.51 - 0.0.80, 3) Network Function Master Account A/c 0.0.50 - Update all Network Function accounts & perform all the Network Functions listed below, 4) Network Function Accounts: i) A/c 0.0.55 - Update Address Book files (0.0.101/102), ii) A/c 0.0.56 - Update Fee schedule (0.0.111), iii) A/c 0.0.57 - Update Exchange Rate (0.0.112).
  case authorizationFailed // = 101

  /// Fee Schedule Proto uploaded but not valid (append or update is required)
  case fileUploadedProtoInvalid // = 102

  /// Fee Schedule Proto uploaded but not valid (append or update is required)
  case fileUploadedProtoNotSavedToDisk // = 103

  /// Fee Schedule Proto File Part uploaded
  case feeScheduleFilePartUploaded // = 104

  /// The change on Exchange Rate exceeds Exchange_Rate_Allowed_Percentage
  case exchangeRateChangeLimitExceeded // = 105

  /// Contract permanent storage exceeded the currently allowable limit
  case maxContractStorageExceeded // = 106

  /// Transfer Account should not be same as Account to be deleted
  case transferAccountSameAsDeleteAccount // = 107
  case totalLedgerBalanceInvalid // = 108

  /// The expiration date/time on a smart contract may not be reduced
  case expirationReductionNotAllowed // = 110

  ///Gas exceeded currently allowable gas limit per transaction
  case maxGasLimitExceeded // = 111

  /// File size exceeded the currently allowable limit
  case maxFileSizeExceeded // = 112

  /// The Topic ID specified is not in the system.
  case invalidTopicID // = 150

  /// A provided admin key was invalid.
  case invalidAdminKey // = 155

  /// A provided submit key was invalid.
  case invalidSubmitKey // = 156

  /// An attempted operation was not authorized (ie - a deleteTopic for a topic with no adminKey).
  case unauthorized // = 157

  /// A ConsensusService message is empty.
  case invalidTopicMessage // = 158

  /// The autoRenewAccount specified is not a valid, active account.
  case invalidAutorenewAccount // = 159

  /// An adminKey was not specified on the topic, so there must not be an autoRenewAccount.
  case autorenewAccountNotAllowed // = 160

  /// The topic has expired, was not automatically renewed, and is in a 7 day grace period before the topic will be
  /// deleted unrecoverably. This error response code will not be returned until autoRenew functionality is supported
  /// by HAPI.
  case topicExpired // = 162

  /// chunk number must be from 1 to total (chunks) inclusive.
  case invalidChunkNumber // = 163

  /// For every chunk, the payer account that is part of initialTransactionID must match the Payer Account of this transaction. The entire initialTransactionID should match the transactionID of the first chunk, but this is not checked or enforced by Hedera except when the chunk number is 1.
  case invalidChunkTransactionID // = 164

  /// Account is frozen and cannot transact with the token
  case accountFrozenForToken // = 165

  /// An involved account already has more than <tt>tokens.maxPerAccount</tt> associations with non-deleted tokens.
  case tokensPerAccountLimitExceeded // = 166

  /// The token is invalid or does not exist
  case invalidTokenID // = 167

  /// Invalid token decimals
  case invalidTokenDecimals // = 168

  /// Invalid token initial supply
  case invalidTokenInitialSupply // = 169

  /// Treasury Account does not exist or is deleted
  case invalidTreasuryAccountForToken // = 170

  /// Token Symbol is not UTF-8 capitalized alphabetical string
  case invalidTokenSymbol // = 171

  /// Freeze key is not set on token
  case tokenHasNoFreezeKey // = 172

  /// Amounts in transfer list are not net zero
  case transfersNotZeroSumForToken // = 173

  /// A token symbol was not provided
  case missingTokenSymbol // = 174

  /// The provided token symbol was too long
  case tokenSymbolTooLong // = 175

  /// KYC must be granted and account does not have KYC granted
  case accountKycNotGrantedForToken // = 176

  /// KYC key is not set on token
  case tokenHasNoKycKey // = 177

  /// Token balance is not sufficient for the transaction
  case insufficientTokenBalance // = 178

  /// Token transactions cannot be executed on deleted token
  case tokenWasDeleted // = 179

  /// Supply key is not set on token
  case tokenHasNoSupplyKey // = 180

  /// Wipe key is not set on token
  case tokenHasNoWipeKey // = 181

  /// The requested token mint amount would cause an invalid total supply
  case invalidTokenMintAmount // = 182

  /// The requested token burn amount would cause an invalid total supply
  case invalidTokenBurnAmount // = 183

  /// A required token-account relationship is missing
  case tokenNotAssociatedToAccount // = 184

  /// The target of a wipe operation was the token treasury account
  case cannotWipeTokenTreasuryAccount // = 185

  /// The provided KYC key was invalid.
  case invalidKycKey // = 186

  /// The provided wipe key was invalid.
  case invalidWipeKey // = 187

  /// The provided freeze key was invalid.
  case invalidFreezeKey // = 188

  /// The provided supply key was invalid.
  case invalidSupplyKey // = 189

  /// Token Name is not provided
  case missingTokenName // = 190

  /// Token Name is too long
  case tokenNameTooLong // = 191

  /// The provided wipe amount must not be negative, zero or bigger than the token holder balance
  case invalidWipingAmount // = 192

  /// Token does not have Admin key set, thus update/delete transactions cannot be performed
  case tokenIsImmutable // = 193

  /// An <tt>associateToken</tt> operation specified a token already associated to the account
  case tokenAlreadyAssociatedToAccount // = 194

  /// An attempted operation is invalid until all token balances for the target account are zero
  case transactionRequiresZeroTokenBalances // = 195

  /// An attempted operation is invalid because the account is a treasury
  case accountIsTreasury // = 196

  /// Same TokenIDs present in the token list
  case tokenIDRepeatedInTokenList // = 197

  /// Exceeded the number of token transfers (both from and to) allowed for token transfer list
  case tokenTransferListSizeLimitExceeded // = 198

  /// TokenTransfersTransactionBody has no TokenTransferList
  case emptyTokenTransferBody // = 199

  /// TokenTransfersTransactionBody has a TokenTransferList with no AccountAmounts
  case emptyTokenTransferAccountAmounts // = 200

  /// The Scheduled entity does not exist; or has now expired, been deleted, or been executed
  case invalidScheduleID // = 201

  /// The Scheduled entity cannot be modified. Admin key not set
  case scheduleIsImmutable // = 202

  /// The provided Scheduled Payer does not exist
  case invalidSchedulePayerID // = 203

  /// The Schedule Create Transaction TransactionID account does not exist
  case invalidScheduleAccountID // = 204

  /// The provided sig map did not contain any new valid signatures from required signers of the scheduled transaction
  case noNewValidSignatures // = 205

  /// The required signers for a scheduled transaction cannot be resolved, for example because they do not exist or have been deleted
  case unresolvableRequiredSigners // = 206

  /// Only whitelisted transaction types may be scheduled
  case scheduledTransactionNotInWhitelist // = 207

  /// At least one of the signatures in the provided sig map did not represent a valid signature for any required signer
  case someSignaturesWereInvalid // = 208

  /// The scheduled field in the TransactionID may not be set to true
  case transactionIDFieldNotAllowed // = 209

  /// A schedule already exists with the same identifying fields of an attempted ScheduleCreate (that is, all fields other than scheduledPayerAccountID)
  case identicalScheduleAlreadyCreated // = 210

  /// A string field in the transaction has a UTF-8 encoding with the prohibited zero byte
  case invalidZeroByteInString // = 211

  /// A schedule being signed or deleted has already been deleted
  case scheduleAlreadyDeleted // = 212

  /// A schedule being signed or deleted has already been executed
  case scheduleAlreadyExecuted // = 213

  /// ConsensusSubmitMessage request's message size is larger than allowed.
  case messageSizeTooLarge // = 214

  /// An operation was assigned to more than one throttle group in a given bucket
  case operationRepeatedInBucketGroups // = 215

  /// The capacity needed to satisfy all opsPerSec groups in a bucket overflowed a signed 8-byte integral type
  case bucketCapacityOverflow // = 216

  /// Given the network size in the address book, the node-level capacity for an operation would never be enough to accept a single request; usually means a bucket burstPeriod should be increased
  case nodeCapacityNotSufficientForOperation // = 217

  /// A bucket was defined without any throttle groups
  case bucketHasNoThrottleGroups // = 218

  /// A throttle group was granted zero opsPerSec
  case throttleGroupHasZeroOpsPerSec // = 219

  /// The throttle definitions file was updated, but some supported operations were not assigned a bucket
  case successButMissingExpectedOperation // = 220

  /// The new contents for the throttle definitions system file were not valid protobuf
  case unparseableThrottleDefinitions // = 221

  /// The new throttle definitions system file were invalid, and no more specific error could be divined
  case invalidThrottleDefinitions // = 222

  /// The transaction references an account which has passed its expiration without renewal funds available, and currently remains in the ledger only because of the grace period given to expired entities
  case accountExpiredAndPendingRemoval // = 223

  /// Invalid token max supply
  case invalidTokenMaxSupply // = 224

  /// Invalid token nft serial number
  case invalidTokenNftSerialNumber // = 225

  /// Invalid nft id
  case invalidNftID // = 226

  /// Nft metadata is too long
  case metadataTooLong // = 227

  /// Repeated operations count exceeds the limit
  case batchSizeLimitExceeded // = 228

  /// The range of data to be gathered exceeds the limit
  case queryRangeLimitExceeded // = 229
  case UNRECOGNIZED(Int)

  public init() {
    self = .ok
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .ok
    case 1: self = .invalidTransaction
    case 2: self = .payerAccountNotFound
    case 3: self = .invalidNodeAccount
    case 4: self = .transactionExpired
    case 5: self = .invalidTransactionStart
    case 6: self = .invalidTransactionDuration
    case 7: self = .invalidSignature
    case 8: self = .memoTooLong
    case 9: self = .insufficientTxFee
    case 10: self = .insufficientPayerBalance
    case 11: self = .duplicateTransaction
    case 12: self = .busy
    case 13: self = .notSupported
    case 14: self = .invalidFileID
    case 15: self = .invalidAccountID
    case 16: self = .invalidContractID
    case 17: self = .invalidTransactionID
    case 18: self = .receiptNotFound
    case 19: self = .recordNotFound
    case 20: self = .invalidSolidityID
    case 21: self = .unknown
    case 22: self = .success
    case 23: self = .failInvalid
    case 24: self = .failFee
    case 25: self = .failBalance
    case 26: self = .keyRequired
    case 27: self = .badEncoding
    case 28: self = .insufficientAccountBalance
    case 29: self = .invalidSolidityAddress
    case 30: self = .insufficientGas
    case 31: self = .contractSizeLimitExceeded
    case 32: self = .localCallModificationException
    case 33: self = .contractRevertExecuted
    case 34: self = .contractExecutionException
    case 35: self = .invalidReceivingNodeAccount
    case 36: self = .missingQueryHeader
    case 37: self = .accountUpdateFailed
    case 38: self = .invalidKeyEncoding
    case 39: self = .nullSolidityAddress
    case 40: self = .contractUpdateFailed
    case 41: self = .invalidQueryHeader
    case 42: self = .invalidFeeSubmitted
    case 43: self = .invalidPayerSignature
    case 44: self = .keyNotProvided
    case 45: self = .invalidExpirationTime
    case 46: self = .noWaclKey
    case 47: self = .fileContentEmpty
    case 48: self = .invalidAccountAmounts
    case 49: self = .emptyTransactionBody
    case 50: self = .invalidTransactionBody
    case 51: self = .invalidSignatureTypeMismatchingKey
    case 52: self = .invalidSignatureCountMismatchingKey
    case 53: self = .emptyLiveHashBody
    case 54: self = .emptyLiveHash
    case 55: self = .emptyLiveHashKeys
    case 56: self = .invalidLiveHashSize
    case 57: self = .emptyQueryBody
    case 58: self = .emptyLiveHashQuery
    case 59: self = .liveHashNotFound
    case 60: self = .accountIDDoesNotExist
    case 61: self = .liveHashAlreadyExists
    case 62: self = .invalidFileWacl
    case 63: self = .serializationFailed
    case 64: self = .transactionOversize
    case 65: self = .transactionTooManyLayers
    case 66: self = .contractDeleted
    case 67: self = .platformNotActive
    case 68: self = .keyPrefixMismatch
    case 69: self = .platformTransactionNotCreated
    case 70: self = .invalidRenewalPeriod
    case 71: self = .invalidPayerAccountID
    case 72: self = .accountDeleted
    case 73: self = .fileDeleted
    case 74: self = .accountRepeatedInAccountAmounts
    case 75: self = .settingNegativeAccountBalance
    case 76: self = .obtainerRequired
    case 77: self = .obtainerSameContractID
    case 78: self = .obtainerDoesNotExist
    case 79: self = .modifyingImmutableContract
    case 80: self = .fileSystemException
    case 81: self = .autorenewDurationNotInRange
    case 82: self = .errorDecodingBytestring
    case 83: self = .contractFileEmpty
    case 84: self = .contractBytecodeEmpty
    case 85: self = .invalidInitialBalance
    case 86: self = .invalidReceiveRecordThreshold
    case 87: self = .invalidSendRecordThreshold
    case 88: self = .accountIsNotGenesisAccount
    case 89: self = .payerAccountUnauthorized
    case 90: self = .invalidFreezeTransactionBody
    case 91: self = .freezeTransactionBodyNotFound
    case 92: self = .transferListSizeLimitExceeded
    case 93: self = .resultSizeLimitExceeded
    case 94: self = .notSpecialAccount
    case 95: self = .contractNegativeGas
    case 96: self = .contractNegativeValue
    case 97: self = .invalidFeeFile
    case 98: self = .invalidExchangeRateFile
    case 99: self = .insufficientLocalCallGas
    case 100: self = .entityNotAllowedToDelete
    case 101: self = .authorizationFailed
    case 102: self = .fileUploadedProtoInvalid
    case 103: self = .fileUploadedProtoNotSavedToDisk
    case 104: self = .feeScheduleFilePartUploaded
    case 105: self = .exchangeRateChangeLimitExceeded
    case 106: self = .maxContractStorageExceeded
    case 107: self = .transferAccountSameAsDeleteAccount
    case 108: self = .totalLedgerBalanceInvalid
    case 110: self = .expirationReductionNotAllowed
    case 111: self = .maxGasLimitExceeded
    case 112: self = .maxFileSizeExceeded
    case 150: self = .invalidTopicID
    case 155: self = .invalidAdminKey
    case 156: self = .invalidSubmitKey
    case 157: self = .unauthorized
    case 158: self = .invalidTopicMessage
    case 159: self = .invalidAutorenewAccount
    case 160: self = .autorenewAccountNotAllowed
    case 162: self = .topicExpired
    case 163: self = .invalidChunkNumber
    case 164: self = .invalidChunkTransactionID
    case 165: self = .accountFrozenForToken
    case 166: self = .tokensPerAccountLimitExceeded
    case 167: self = .invalidTokenID
    case 168: self = .invalidTokenDecimals
    case 169: self = .invalidTokenInitialSupply
    case 170: self = .invalidTreasuryAccountForToken
    case 171: self = .invalidTokenSymbol
    case 172: self = .tokenHasNoFreezeKey
    case 173: self = .transfersNotZeroSumForToken
    case 174: self = .missingTokenSymbol
    case 175: self = .tokenSymbolTooLong
    case 176: self = .accountKycNotGrantedForToken
    case 177: self = .tokenHasNoKycKey
    case 178: self = .insufficientTokenBalance
    case 179: self = .tokenWasDeleted
    case 180: self = .tokenHasNoSupplyKey
    case 181: self = .tokenHasNoWipeKey
    case 182: self = .invalidTokenMintAmount
    case 183: self = .invalidTokenBurnAmount
    case 184: self = .tokenNotAssociatedToAccount
    case 185: self = .cannotWipeTokenTreasuryAccount
    case 186: self = .invalidKycKey
    case 187: self = .invalidWipeKey
    case 188: self = .invalidFreezeKey
    case 189: self = .invalidSupplyKey
    case 190: self = .missingTokenName
    case 191: self = .tokenNameTooLong
    case 192: self = .invalidWipingAmount
    case 193: self = .tokenIsImmutable
    case 194: self = .tokenAlreadyAssociatedToAccount
    case 195: self = .transactionRequiresZeroTokenBalances
    case 196: self = .accountIsTreasury
    case 197: self = .tokenIDRepeatedInTokenList
    case 198: self = .tokenTransferListSizeLimitExceeded
    case 199: self = .emptyTokenTransferBody
    case 200: self = .emptyTokenTransferAccountAmounts
    case 201: self = .invalidScheduleID
    case 202: self = .scheduleIsImmutable
    case 203: self = .invalidSchedulePayerID
    case 204: self = .invalidScheduleAccountID
    case 205: self = .noNewValidSignatures
    case 206: self = .unresolvableRequiredSigners
    case 207: self = .scheduledTransactionNotInWhitelist
    case 208: self = .someSignaturesWereInvalid
    case 209: self = .transactionIDFieldNotAllowed
    case 210: self = .identicalScheduleAlreadyCreated
    case 211: self = .invalidZeroByteInString
    case 212: self = .scheduleAlreadyDeleted
    case 213: self = .scheduleAlreadyExecuted
    case 214: self = .messageSizeTooLarge
    case 215: self = .operationRepeatedInBucketGroups
    case 216: self = .bucketCapacityOverflow
    case 217: self = .nodeCapacityNotSufficientForOperation
    case 218: self = .bucketHasNoThrottleGroups
    case 219: self = .throttleGroupHasZeroOpsPerSec
    case 220: self = .successButMissingExpectedOperation
    case 221: self = .unparseableThrottleDefinitions
    case 222: self = .invalidThrottleDefinitions
    case 223: self = .accountExpiredAndPendingRemoval
    case 224: self = .invalidTokenMaxSupply
    case 225: self = .invalidTokenNftSerialNumber
    case 226: self = .invalidNftID
    case 227: self = .metadataTooLong
    case 228: self = .batchSizeLimitExceeded
    case 229: self = .queryRangeLimitExceeded
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .ok: return 0
    case .invalidTransaction: return 1
    case .payerAccountNotFound: return 2
    case .invalidNodeAccount: return 3
    case .transactionExpired: return 4
    case .invalidTransactionStart: return 5
    case .invalidTransactionDuration: return 6
    case .invalidSignature: return 7
    case .memoTooLong: return 8
    case .insufficientTxFee: return 9
    case .insufficientPayerBalance: return 10
    case .duplicateTransaction: return 11
    case .busy: return 12
    case .notSupported: return 13
    case .invalidFileID: return 14
    case .invalidAccountID: return 15
    case .invalidContractID: return 16
    case .invalidTransactionID: return 17
    case .receiptNotFound: return 18
    case .recordNotFound: return 19
    case .invalidSolidityID: return 20
    case .unknown: return 21
    case .success: return 22
    case .failInvalid: return 23
    case .failFee: return 24
    case .failBalance: return 25
    case .keyRequired: return 26
    case .badEncoding: return 27
    case .insufficientAccountBalance: return 28
    case .invalidSolidityAddress: return 29
    case .insufficientGas: return 30
    case .contractSizeLimitExceeded: return 31
    case .localCallModificationException: return 32
    case .contractRevertExecuted: return 33
    case .contractExecutionException: return 34
    case .invalidReceivingNodeAccount: return 35
    case .missingQueryHeader: return 36
    case .accountUpdateFailed: return 37
    case .invalidKeyEncoding: return 38
    case .nullSolidityAddress: return 39
    case .contractUpdateFailed: return 40
    case .invalidQueryHeader: return 41
    case .invalidFeeSubmitted: return 42
    case .invalidPayerSignature: return 43
    case .keyNotProvided: return 44
    case .invalidExpirationTime: return 45
    case .noWaclKey: return 46
    case .fileContentEmpty: return 47
    case .invalidAccountAmounts: return 48
    case .emptyTransactionBody: return 49
    case .invalidTransactionBody: return 50
    case .invalidSignatureTypeMismatchingKey: return 51
    case .invalidSignatureCountMismatchingKey: return 52
    case .emptyLiveHashBody: return 53
    case .emptyLiveHash: return 54
    case .emptyLiveHashKeys: return 55
    case .invalidLiveHashSize: return 56
    case .emptyQueryBody: return 57
    case .emptyLiveHashQuery: return 58
    case .liveHashNotFound: return 59
    case .accountIDDoesNotExist: return 60
    case .liveHashAlreadyExists: return 61
    case .invalidFileWacl: return 62
    case .serializationFailed: return 63
    case .transactionOversize: return 64
    case .transactionTooManyLayers: return 65
    case .contractDeleted: return 66
    case .platformNotActive: return 67
    case .keyPrefixMismatch: return 68
    case .platformTransactionNotCreated: return 69
    case .invalidRenewalPeriod: return 70
    case .invalidPayerAccountID: return 71
    case .accountDeleted: return 72
    case .fileDeleted: return 73
    case .accountRepeatedInAccountAmounts: return 74
    case .settingNegativeAccountBalance: return 75
    case .obtainerRequired: return 76
    case .obtainerSameContractID: return 77
    case .obtainerDoesNotExist: return 78
    case .modifyingImmutableContract: return 79
    case .fileSystemException: return 80
    case .autorenewDurationNotInRange: return 81
    case .errorDecodingBytestring: return 82
    case .contractFileEmpty: return 83
    case .contractBytecodeEmpty: return 84
    case .invalidInitialBalance: return 85
    case .invalidReceiveRecordThreshold: return 86
    case .invalidSendRecordThreshold: return 87
    case .accountIsNotGenesisAccount: return 88
    case .payerAccountUnauthorized: return 89
    case .invalidFreezeTransactionBody: return 90
    case .freezeTransactionBodyNotFound: return 91
    case .transferListSizeLimitExceeded: return 92
    case .resultSizeLimitExceeded: return 93
    case .notSpecialAccount: return 94
    case .contractNegativeGas: return 95
    case .contractNegativeValue: return 96
    case .invalidFeeFile: return 97
    case .invalidExchangeRateFile: return 98
    case .insufficientLocalCallGas: return 99
    case .entityNotAllowedToDelete: return 100
    case .authorizationFailed: return 101
    case .fileUploadedProtoInvalid: return 102
    case .fileUploadedProtoNotSavedToDisk: return 103
    case .feeScheduleFilePartUploaded: return 104
    case .exchangeRateChangeLimitExceeded: return 105
    case .maxContractStorageExceeded: return 106
    case .transferAccountSameAsDeleteAccount: return 107
    case .totalLedgerBalanceInvalid: return 108
    case .expirationReductionNotAllowed: return 110
    case .maxGasLimitExceeded: return 111
    case .maxFileSizeExceeded: return 112
    case .invalidTopicID: return 150
    case .invalidAdminKey: return 155
    case .invalidSubmitKey: return 156
    case .unauthorized: return 157
    case .invalidTopicMessage: return 158
    case .invalidAutorenewAccount: return 159
    case .autorenewAccountNotAllowed: return 160
    case .topicExpired: return 162
    case .invalidChunkNumber: return 163
    case .invalidChunkTransactionID: return 164
    case .accountFrozenForToken: return 165
    case .tokensPerAccountLimitExceeded: return 166
    case .invalidTokenID: return 167
    case .invalidTokenDecimals: return 168
    case .invalidTokenInitialSupply: return 169
    case .invalidTreasuryAccountForToken: return 170
    case .invalidTokenSymbol: return 171
    case .tokenHasNoFreezeKey: return 172
    case .transfersNotZeroSumForToken: return 173
    case .missingTokenSymbol: return 174
    case .tokenSymbolTooLong: return 175
    case .accountKycNotGrantedForToken: return 176
    case .tokenHasNoKycKey: return 177
    case .insufficientTokenBalance: return 178
    case .tokenWasDeleted: return 179
    case .tokenHasNoSupplyKey: return 180
    case .tokenHasNoWipeKey: return 181
    case .invalidTokenMintAmount: return 182
    case .invalidTokenBurnAmount: return 183
    case .tokenNotAssociatedToAccount: return 184
    case .cannotWipeTokenTreasuryAccount: return 185
    case .invalidKycKey: return 186
    case .invalidWipeKey: return 187
    case .invalidFreezeKey: return 188
    case .invalidSupplyKey: return 189
    case .missingTokenName: return 190
    case .tokenNameTooLong: return 191
    case .invalidWipingAmount: return 192
    case .tokenIsImmutable: return 193
    case .tokenAlreadyAssociatedToAccount: return 194
    case .transactionRequiresZeroTokenBalances: return 195
    case .accountIsTreasury: return 196
    case .tokenIDRepeatedInTokenList: return 197
    case .tokenTransferListSizeLimitExceeded: return 198
    case .emptyTokenTransferBody: return 199
    case .emptyTokenTransferAccountAmounts: return 200
    case .invalidScheduleID: return 201
    case .scheduleIsImmutable: return 202
    case .invalidSchedulePayerID: return 203
    case .invalidScheduleAccountID: return 204
    case .noNewValidSignatures: return 205
    case .unresolvableRequiredSigners: return 206
    case .scheduledTransactionNotInWhitelist: return 207
    case .someSignaturesWereInvalid: return 208
    case .transactionIDFieldNotAllowed: return 209
    case .identicalScheduleAlreadyCreated: return 210
    case .invalidZeroByteInString: return 211
    case .scheduleAlreadyDeleted: return 212
    case .scheduleAlreadyExecuted: return 213
    case .messageSizeTooLarge: return 214
    case .operationRepeatedInBucketGroups: return 215
    case .bucketCapacityOverflow: return 216
    case .nodeCapacityNotSufficientForOperation: return 217
    case .bucketHasNoThrottleGroups: return 218
    case .throttleGroupHasZeroOpsPerSec: return 219
    case .successButMissingExpectedOperation: return 220
    case .unparseableThrottleDefinitions: return 221
    case .invalidThrottleDefinitions: return 222
    case .accountExpiredAndPendingRemoval: return 223
    case .invalidTokenMaxSupply: return 224
    case .invalidTokenNftSerialNumber: return 225
    case .invalidNftID: return 226
    case .metadataTooLong: return 227
    case .batchSizeLimitExceeded: return 228
    case .queryRangeLimitExceeded: return 229
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Proto_ResponseCodeEnum: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Proto_ResponseCodeEnum] = [
    .ok,
    .invalidTransaction,
    .payerAccountNotFound,
    .invalidNodeAccount,
    .transactionExpired,
    .invalidTransactionStart,
    .invalidTransactionDuration,
    .invalidSignature,
    .memoTooLong,
    .insufficientTxFee,
    .insufficientPayerBalance,
    .duplicateTransaction,
    .busy,
    .notSupported,
    .invalidFileID,
    .invalidAccountID,
    .invalidContractID,
    .invalidTransactionID,
    .receiptNotFound,
    .recordNotFound,
    .invalidSolidityID,
    .unknown,
    .success,
    .failInvalid,
    .failFee,
    .failBalance,
    .keyRequired,
    .badEncoding,
    .insufficientAccountBalance,
    .invalidSolidityAddress,
    .insufficientGas,
    .contractSizeLimitExceeded,
    .localCallModificationException,
    .contractRevertExecuted,
    .contractExecutionException,
    .invalidReceivingNodeAccount,
    .missingQueryHeader,
    .accountUpdateFailed,
    .invalidKeyEncoding,
    .nullSolidityAddress,
    .contractUpdateFailed,
    .invalidQueryHeader,
    .invalidFeeSubmitted,
    .invalidPayerSignature,
    .keyNotProvided,
    .invalidExpirationTime,
    .noWaclKey,
    .fileContentEmpty,
    .invalidAccountAmounts,
    .emptyTransactionBody,
    .invalidTransactionBody,
    .invalidSignatureTypeMismatchingKey,
    .invalidSignatureCountMismatchingKey,
    .emptyLiveHashBody,
    .emptyLiveHash,
    .emptyLiveHashKeys,
    .invalidLiveHashSize,
    .emptyQueryBody,
    .emptyLiveHashQuery,
    .liveHashNotFound,
    .accountIDDoesNotExist,
    .liveHashAlreadyExists,
    .invalidFileWacl,
    .serializationFailed,
    .transactionOversize,
    .transactionTooManyLayers,
    .contractDeleted,
    .platformNotActive,
    .keyPrefixMismatch,
    .platformTransactionNotCreated,
    .invalidRenewalPeriod,
    .invalidPayerAccountID,
    .accountDeleted,
    .fileDeleted,
    .accountRepeatedInAccountAmounts,
    .settingNegativeAccountBalance,
    .obtainerRequired,
    .obtainerSameContractID,
    .obtainerDoesNotExist,
    .modifyingImmutableContract,
    .fileSystemException,
    .autorenewDurationNotInRange,
    .errorDecodingBytestring,
    .contractFileEmpty,
    .contractBytecodeEmpty,
    .invalidInitialBalance,
    .invalidReceiveRecordThreshold,
    .invalidSendRecordThreshold,
    .accountIsNotGenesisAccount,
    .payerAccountUnauthorized,
    .invalidFreezeTransactionBody,
    .freezeTransactionBodyNotFound,
    .transferListSizeLimitExceeded,
    .resultSizeLimitExceeded,
    .notSpecialAccount,
    .contractNegativeGas,
    .contractNegativeValue,
    .invalidFeeFile,
    .invalidExchangeRateFile,
    .insufficientLocalCallGas,
    .entityNotAllowedToDelete,
    .authorizationFailed,
    .fileUploadedProtoInvalid,
    .fileUploadedProtoNotSavedToDisk,
    .feeScheduleFilePartUploaded,
    .exchangeRateChangeLimitExceeded,
    .maxContractStorageExceeded,
    .transferAccountSameAsDeleteAccount,
    .totalLedgerBalanceInvalid,
    .expirationReductionNotAllowed,
    .maxGasLimitExceeded,
    .maxFileSizeExceeded,
    .invalidTopicID,
    .invalidAdminKey,
    .invalidSubmitKey,
    .unauthorized,
    .invalidTopicMessage,
    .invalidAutorenewAccount,
    .autorenewAccountNotAllowed,
    .topicExpired,
    .invalidChunkNumber,
    .invalidChunkTransactionID,
    .accountFrozenForToken,
    .tokensPerAccountLimitExceeded,
    .invalidTokenID,
    .invalidTokenDecimals,
    .invalidTokenInitialSupply,
    .invalidTreasuryAccountForToken,
    .invalidTokenSymbol,
    .tokenHasNoFreezeKey,
    .transfersNotZeroSumForToken,
    .missingTokenSymbol,
    .tokenSymbolTooLong,
    .accountKycNotGrantedForToken,
    .tokenHasNoKycKey,
    .insufficientTokenBalance,
    .tokenWasDeleted,
    .tokenHasNoSupplyKey,
    .tokenHasNoWipeKey,
    .invalidTokenMintAmount,
    .invalidTokenBurnAmount,
    .tokenNotAssociatedToAccount,
    .cannotWipeTokenTreasuryAccount,
    .invalidKycKey,
    .invalidWipeKey,
    .invalidFreezeKey,
    .invalidSupplyKey,
    .missingTokenName,
    .tokenNameTooLong,
    .invalidWipingAmount,
    .tokenIsImmutable,
    .tokenAlreadyAssociatedToAccount,
    .transactionRequiresZeroTokenBalances,
    .accountIsTreasury,
    .tokenIDRepeatedInTokenList,
    .tokenTransferListSizeLimitExceeded,
    .emptyTokenTransferBody,
    .emptyTokenTransferAccountAmounts,
    .invalidScheduleID,
    .scheduleIsImmutable,
    .invalidSchedulePayerID,
    .invalidScheduleAccountID,
    .noNewValidSignatures,
    .unresolvableRequiredSigners,
    .scheduledTransactionNotInWhitelist,
    .someSignaturesWereInvalid,
    .transactionIDFieldNotAllowed,
    .identicalScheduleAlreadyCreated,
    .invalidZeroByteInString,
    .scheduleAlreadyDeleted,
    .scheduleAlreadyExecuted,
    .messageSizeTooLarge,
    .operationRepeatedInBucketGroups,
    .bucketCapacityOverflow,
    .nodeCapacityNotSufficientForOperation,
    .bucketHasNoThrottleGroups,
    .throttleGroupHasZeroOpsPerSec,
    .successButMissingExpectedOperation,
    .unparseableThrottleDefinitions,
    .invalidThrottleDefinitions,
    .accountExpiredAndPendingRemoval,
    .invalidTokenMaxSupply,
    .invalidTokenNftSerialNumber,
    .invalidNftID,
    .metadataTooLong,
    .batchSizeLimitExceeded,
    .queryRangeLimitExceeded,
  ]
}

#endif  // swift(>=4.2)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Proto_ResponseCodeEnum: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "OK"),
    1: .same(proto: "INVALID_TRANSACTION"),
    2: .same(proto: "PAYER_ACCOUNT_NOT_FOUND"),
    3: .same(proto: "INVALID_NODE_ACCOUNT"),
    4: .same(proto: "TRANSACTION_EXPIRED"),
    5: .same(proto: "INVALID_TRANSACTION_START"),
    6: .same(proto: "INVALID_TRANSACTION_DURATION"),
    7: .same(proto: "INVALID_SIGNATURE"),
    8: .same(proto: "MEMO_TOO_LONG"),
    9: .same(proto: "INSUFFICIENT_TX_FEE"),
    10: .same(proto: "INSUFFICIENT_PAYER_BALANCE"),
    11: .same(proto: "DUPLICATE_TRANSACTION"),
    12: .same(proto: "BUSY"),
    13: .same(proto: "NOT_SUPPORTED"),
    14: .same(proto: "INVALID_FILE_ID"),
    15: .same(proto: "INVALID_ACCOUNT_ID"),
    16: .same(proto: "INVALID_CONTRACT_ID"),
    17: .same(proto: "INVALID_TRANSACTION_ID"),
    18: .same(proto: "RECEIPT_NOT_FOUND"),
    19: .same(proto: "RECORD_NOT_FOUND"),
    20: .same(proto: "INVALID_SOLIDITY_ID"),
    21: .same(proto: "UNKNOWN"),
    22: .same(proto: "SUCCESS"),
    23: .same(proto: "FAIL_INVALID"),
    24: .same(proto: "FAIL_FEE"),
    25: .same(proto: "FAIL_BALANCE"),
    26: .same(proto: "KEY_REQUIRED"),
    27: .same(proto: "BAD_ENCODING"),
    28: .same(proto: "INSUFFICIENT_ACCOUNT_BALANCE"),
    29: .same(proto: "INVALID_SOLIDITY_ADDRESS"),
    30: .same(proto: "INSUFFICIENT_GAS"),
    31: .same(proto: "CONTRACT_SIZE_LIMIT_EXCEEDED"),
    32: .same(proto: "LOCAL_CALL_MODIFICATION_EXCEPTION"),
    33: .same(proto: "CONTRACT_REVERT_EXECUTED"),
    34: .same(proto: "CONTRACT_EXECUTION_EXCEPTION"),
    35: .same(proto: "INVALID_RECEIVING_NODE_ACCOUNT"),
    36: .same(proto: "MISSING_QUERY_HEADER"),
    37: .same(proto: "ACCOUNT_UPDATE_FAILED"),
    38: .same(proto: "INVALID_KEY_ENCODING"),
    39: .same(proto: "NULL_SOLIDITY_ADDRESS"),
    40: .same(proto: "CONTRACT_UPDATE_FAILED"),
    41: .same(proto: "INVALID_QUERY_HEADER"),
    42: .same(proto: "INVALID_FEE_SUBMITTED"),
    43: .same(proto: "INVALID_PAYER_SIGNATURE"),
    44: .same(proto: "KEY_NOT_PROVIDED"),
    45: .same(proto: "INVALID_EXPIRATION_TIME"),
    46: .same(proto: "NO_WACL_KEY"),
    47: .same(proto: "FILE_CONTENT_EMPTY"),
    48: .same(proto: "INVALID_ACCOUNT_AMOUNTS"),
    49: .same(proto: "EMPTY_TRANSACTION_BODY"),
    50: .same(proto: "INVALID_TRANSACTION_BODY"),
    51: .same(proto: "INVALID_SIGNATURE_TYPE_MISMATCHING_KEY"),
    52: .same(proto: "INVALID_SIGNATURE_COUNT_MISMATCHING_KEY"),
    53: .same(proto: "EMPTY_LIVE_HASH_BODY"),
    54: .same(proto: "EMPTY_LIVE_HASH"),
    55: .same(proto: "EMPTY_LIVE_HASH_KEYS"),
    56: .same(proto: "INVALID_LIVE_HASH_SIZE"),
    57: .same(proto: "EMPTY_QUERY_BODY"),
    58: .same(proto: "EMPTY_LIVE_HASH_QUERY"),
    59: .same(proto: "LIVE_HASH_NOT_FOUND"),
    60: .same(proto: "ACCOUNT_ID_DOES_NOT_EXIST"),
    61: .same(proto: "LIVE_HASH_ALREADY_EXISTS"),
    62: .same(proto: "INVALID_FILE_WACL"),
    63: .same(proto: "SERIALIZATION_FAILED"),
    64: .same(proto: "TRANSACTION_OVERSIZE"),
    65: .same(proto: "TRANSACTION_TOO_MANY_LAYERS"),
    66: .same(proto: "CONTRACT_DELETED"),
    67: .same(proto: "PLATFORM_NOT_ACTIVE"),
    68: .same(proto: "KEY_PREFIX_MISMATCH"),
    69: .same(proto: "PLATFORM_TRANSACTION_NOT_CREATED"),
    70: .same(proto: "INVALID_RENEWAL_PERIOD"),
    71: .same(proto: "INVALID_PAYER_ACCOUNT_ID"),
    72: .same(proto: "ACCOUNT_DELETED"),
    73: .same(proto: "FILE_DELETED"),
    74: .same(proto: "ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS"),
    75: .same(proto: "SETTING_NEGATIVE_ACCOUNT_BALANCE"),
    76: .same(proto: "OBTAINER_REQUIRED"),
    77: .same(proto: "OBTAINER_SAME_CONTRACT_ID"),
    78: .same(proto: "OBTAINER_DOES_NOT_EXIST"),
    79: .same(proto: "MODIFYING_IMMUTABLE_CONTRACT"),
    80: .same(proto: "FILE_SYSTEM_EXCEPTION"),
    81: .same(proto: "AUTORENEW_DURATION_NOT_IN_RANGE"),
    82: .same(proto: "ERROR_DECODING_BYTESTRING"),
    83: .same(proto: "CONTRACT_FILE_EMPTY"),
    84: .same(proto: "CONTRACT_BYTECODE_EMPTY"),
    85: .same(proto: "INVALID_INITIAL_BALANCE"),
    86: .same(proto: "INVALID_RECEIVE_RECORD_THRESHOLD"),
    87: .same(proto: "INVALID_SEND_RECORD_THRESHOLD"),
    88: .same(proto: "ACCOUNT_IS_NOT_GENESIS_ACCOUNT"),
    89: .same(proto: "PAYER_ACCOUNT_UNAUTHORIZED"),
    90: .same(proto: "INVALID_FREEZE_TRANSACTION_BODY"),
    91: .same(proto: "FREEZE_TRANSACTION_BODY_NOT_FOUND"),
    92: .same(proto: "TRANSFER_LIST_SIZE_LIMIT_EXCEEDED"),
    93: .same(proto: "RESULT_SIZE_LIMIT_EXCEEDED"),
    94: .same(proto: "NOT_SPECIAL_ACCOUNT"),
    95: .same(proto: "CONTRACT_NEGATIVE_GAS"),
    96: .same(proto: "CONTRACT_NEGATIVE_VALUE"),
    97: .same(proto: "INVALID_FEE_FILE"),
    98: .same(proto: "INVALID_EXCHANGE_RATE_FILE"),
    99: .same(proto: "INSUFFICIENT_LOCAL_CALL_GAS"),
    100: .same(proto: "ENTITY_NOT_ALLOWED_TO_DELETE"),
    101: .same(proto: "AUTHORIZATION_FAILED"),
    102: .same(proto: "FILE_UPLOADED_PROTO_INVALID"),
    103: .same(proto: "FILE_UPLOADED_PROTO_NOT_SAVED_TO_DISK"),
    104: .same(proto: "FEE_SCHEDULE_FILE_PART_UPLOADED"),
    105: .same(proto: "EXCHANGE_RATE_CHANGE_LIMIT_EXCEEDED"),
    106: .same(proto: "MAX_CONTRACT_STORAGE_EXCEEDED"),
    107: .same(proto: "TRANSFER_ACCOUNT_SAME_AS_DELETE_ACCOUNT"),
    108: .same(proto: "TOTAL_LEDGER_BALANCE_INVALID"),
    110: .same(proto: "EXPIRATION_REDUCTION_NOT_ALLOWED"),
    111: .same(proto: "MAX_GAS_LIMIT_EXCEEDED"),
    112: .same(proto: "MAX_FILE_SIZE_EXCEEDED"),
    150: .same(proto: "INVALID_TOPIC_ID"),
    155: .same(proto: "INVALID_ADMIN_KEY"),
    156: .same(proto: "INVALID_SUBMIT_KEY"),
    157: .same(proto: "UNAUTHORIZED"),
    158: .same(proto: "INVALID_TOPIC_MESSAGE"),
    159: .same(proto: "INVALID_AUTORENEW_ACCOUNT"),
    160: .same(proto: "AUTORENEW_ACCOUNT_NOT_ALLOWED"),
    162: .same(proto: "TOPIC_EXPIRED"),
    163: .same(proto: "INVALID_CHUNK_NUMBER"),
    164: .same(proto: "INVALID_CHUNK_TRANSACTION_ID"),
    165: .same(proto: "ACCOUNT_FROZEN_FOR_TOKEN"),
    166: .same(proto: "TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED"),
    167: .same(proto: "INVALID_TOKEN_ID"),
    168: .same(proto: "INVALID_TOKEN_DECIMALS"),
    169: .same(proto: "INVALID_TOKEN_INITIAL_SUPPLY"),
    170: .same(proto: "INVALID_TREASURY_ACCOUNT_FOR_TOKEN"),
    171: .same(proto: "INVALID_TOKEN_SYMBOL"),
    172: .same(proto: "TOKEN_HAS_NO_FREEZE_KEY"),
    173: .same(proto: "TRANSFERS_NOT_ZERO_SUM_FOR_TOKEN"),
    174: .same(proto: "MISSING_TOKEN_SYMBOL"),
    175: .same(proto: "TOKEN_SYMBOL_TOO_LONG"),
    176: .same(proto: "ACCOUNT_KYC_NOT_GRANTED_FOR_TOKEN"),
    177: .same(proto: "TOKEN_HAS_NO_KYC_KEY"),
    178: .same(proto: "INSUFFICIENT_TOKEN_BALANCE"),
    179: .same(proto: "TOKEN_WAS_DELETED"),
    180: .same(proto: "TOKEN_HAS_NO_SUPPLY_KEY"),
    181: .same(proto: "TOKEN_HAS_NO_WIPE_KEY"),
    182: .same(proto: "INVALID_TOKEN_MINT_AMOUNT"),
    183: .same(proto: "INVALID_TOKEN_BURN_AMOUNT"),
    184: .same(proto: "TOKEN_NOT_ASSOCIATED_TO_ACCOUNT"),
    185: .same(proto: "CANNOT_WIPE_TOKEN_TREASURY_ACCOUNT"),
    186: .same(proto: "INVALID_KYC_KEY"),
    187: .same(proto: "INVALID_WIPE_KEY"),
    188: .same(proto: "INVALID_FREEZE_KEY"),
    189: .same(proto: "INVALID_SUPPLY_KEY"),
    190: .same(proto: "MISSING_TOKEN_NAME"),
    191: .same(proto: "TOKEN_NAME_TOO_LONG"),
    192: .same(proto: "INVALID_WIPING_AMOUNT"),
    193: .same(proto: "TOKEN_IS_IMMUTABLE"),
    194: .same(proto: "TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT"),
    195: .same(proto: "TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES"),
    196: .same(proto: "ACCOUNT_IS_TREASURY"),
    197: .same(proto: "TOKEN_ID_REPEATED_IN_TOKEN_LIST"),
    198: .same(proto: "TOKEN_TRANSFER_LIST_SIZE_LIMIT_EXCEEDED"),
    199: .same(proto: "EMPTY_TOKEN_TRANSFER_BODY"),
    200: .same(proto: "EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS"),
    201: .same(proto: "INVALID_SCHEDULE_ID"),
    202: .same(proto: "SCHEDULE_IS_IMMUTABLE"),
    203: .same(proto: "INVALID_SCHEDULE_PAYER_ID"),
    204: .same(proto: "INVALID_SCHEDULE_ACCOUNT_ID"),
    205: .same(proto: "NO_NEW_VALID_SIGNATURES"),
    206: .same(proto: "UNRESOLVABLE_REQUIRED_SIGNERS"),
    207: .same(proto: "SCHEDULED_TRANSACTION_NOT_IN_WHITELIST"),
    208: .same(proto: "SOME_SIGNATURES_WERE_INVALID"),
    209: .same(proto: "TRANSACTION_ID_FIELD_NOT_ALLOWED"),
    210: .same(proto: "IDENTICAL_SCHEDULE_ALREADY_CREATED"),
    211: .same(proto: "INVALID_ZERO_BYTE_IN_STRING"),
    212: .same(proto: "SCHEDULE_ALREADY_DELETED"),
    213: .same(proto: "SCHEDULE_ALREADY_EXECUTED"),
    214: .same(proto: "MESSAGE_SIZE_TOO_LARGE"),
    215: .same(proto: "OPERATION_REPEATED_IN_BUCKET_GROUPS"),
    216: .same(proto: "BUCKET_CAPACITY_OVERFLOW"),
    217: .same(proto: "NODE_CAPACITY_NOT_SUFFICIENT_FOR_OPERATION"),
    218: .same(proto: "BUCKET_HAS_NO_THROTTLE_GROUPS"),
    219: .same(proto: "THROTTLE_GROUP_HAS_ZERO_OPS_PER_SEC"),
    220: .same(proto: "SUCCESS_BUT_MISSING_EXPECTED_OPERATION"),
    221: .same(proto: "UNPARSEABLE_THROTTLE_DEFINITIONS"),
    222: .same(proto: "INVALID_THROTTLE_DEFINITIONS"),
    223: .same(proto: "ACCOUNT_EXPIRED_AND_PENDING_REMOVAL"),
    224: .same(proto: "INVALID_TOKEN_MAX_SUPPLY"),
    225: .same(proto: "INVALID_TOKEN_NFT_SERIAL_NUMBER"),
    226: .same(proto: "INVALID_NFT_ID"),
    227: .same(proto: "METADATA_TOO_LONG"),
    228: .same(proto: "BATCH_SIZE_LIMIT_EXCEEDED"),
    229: .same(proto: "QUERY_RANGE_LIMIT_EXCEEDED"),
  ]
}
