//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ConsensusService.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf
import HederaProtoServices


///
/// The Mirror Service provides the ability to query a stream of Hedera Consensus Service (HCS) messages for an
/// HCS Topic via a specific (possibly open-ended) time range.
///
/// Usage: instantiate `Com_Hedera_Mirror_Api_Proto_ConsensusServiceClient`, then call methods of this protocol to make API calls.
public protocol Com_Hedera_Mirror_Api_Proto_ConsensusServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Com_Hedera_Mirror_Api_Proto_ConsensusServiceClientInterceptorFactoryProtocol? { get }

  func subscribeTopic(
    _ request: Com_Hedera_Mirror_Api_Proto_ConsensusTopicQuery,
    callOptions: CallOptions?,
    handler: @escaping (Com_Hedera_Mirror_Api_Proto_ConsensusTopicResponse) -> Void
  ) -> ServerStreamingCall<Com_Hedera_Mirror_Api_Proto_ConsensusTopicQuery, Com_Hedera_Mirror_Api_Proto_ConsensusTopicResponse>
}

extension Com_Hedera_Mirror_Api_Proto_ConsensusServiceClientProtocol {
  public var serviceName: String {
    return "com.hedera.mirror.api.proto.ConsensusService"
  }

  /// Server streaming call to subscribeTopic
  ///
  /// - Parameters:
  ///   - request: Request to send to subscribeTopic.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func subscribeTopic(
    _ request: Com_Hedera_Mirror_Api_Proto_ConsensusTopicQuery,
    callOptions: CallOptions? = nil,
    handler: @escaping (Com_Hedera_Mirror_Api_Proto_ConsensusTopicResponse) -> Void
  ) -> ServerStreamingCall<Com_Hedera_Mirror_Api_Proto_ConsensusTopicQuery, Com_Hedera_Mirror_Api_Proto_ConsensusTopicResponse> {
    return self.makeServerStreamingCall(
      path: "/com.hedera.mirror.api.proto.ConsensusService/subscribeTopic",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makesubscribeTopicInterceptors() ?? [],
      handler: handler
    )
  }
}

public protocol Com_Hedera_Mirror_Api_Proto_ConsensusServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'subscribeTopic'.
  func makesubscribeTopicInterceptors() -> [ClientInterceptor<Com_Hedera_Mirror_Api_Proto_ConsensusTopicQuery, Com_Hedera_Mirror_Api_Proto_ConsensusTopicResponse>]
}

public final class Com_Hedera_Mirror_Api_Proto_ConsensusServiceClient: Com_Hedera_Mirror_Api_Proto_ConsensusServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Com_Hedera_Mirror_Api_Proto_ConsensusServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the com.hedera.mirror.api.proto.ConsensusService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Hedera_Mirror_Api_Proto_ConsensusServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

///
/// The Mirror Service provides the ability to query a stream of Hedera Consensus Service (HCS) messages for an
/// HCS Topic via a specific (possibly open-ended) time range.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Com_Hedera_Mirror_Api_Proto_ConsensusServiceProvider: CallHandlerProvider {
  var interceptors: Com_Hedera_Mirror_Api_Proto_ConsensusServiceServerInterceptorFactoryProtocol? { get }

  func subscribeTopic(request: Com_Hedera_Mirror_Api_Proto_ConsensusTopicQuery, context: StreamingResponseCallContext<Com_Hedera_Mirror_Api_Proto_ConsensusTopicResponse>) -> EventLoopFuture<GRPCStatus>
}

extension Com_Hedera_Mirror_Api_Proto_ConsensusServiceProvider {
  public var serviceName: Substring { return "com.hedera.mirror.api.proto.ConsensusService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "subscribeTopic":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Hedera_Mirror_Api_Proto_ConsensusTopicQuery>(),
        responseSerializer: ProtobufSerializer<Com_Hedera_Mirror_Api_Proto_ConsensusTopicResponse>(),
        interceptors: self.interceptors?.makesubscribeTopicInterceptors() ?? [],
        userFunction: self.subscribeTopic(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol Com_Hedera_Mirror_Api_Proto_ConsensusServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'subscribeTopic'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makesubscribeTopicInterceptors() -> [ServerInterceptor<Com_Hedera_Mirror_Api_Proto_ConsensusTopicQuery, Com_Hedera_Mirror_Api_Proto_ConsensusTopicResponse>]
}
